require 'nene'
require 'rotor'
require 'rotor-quick.makers'

local AlpinistState = @enum{
  Climbing = 0,
  Shooting,
  Dying,
  Dead,
}

global Game.Components.AlpinistControllable = @record{
  climb_speed: number,
  shoot_interval: number,
  state: AlpinistState,
}

local AlpinistControllable = Game.Components.AlpinistControllable
## impl_is_component(AlpinistControllable)

global Game.Components.AlpinistControllable.AlpinistState = AlpinistState
