require 'nene'
require 'rotor'
require 'irene.makers'

local AlpinistState = @enum{
  Climbing = 0,
  Shooting,
  Dying,
  Dead,
}

local AlpinistControllable = @record{
  climb_speed: number,
  shoot_interval: number,
  state: AlpinistState,
}
## Irene.impl_is_component(AlpinistControllable)

global Game.Comps.AlpinistControllable = @AlpinistControllable
global Game.Comps.AlpinistControllable.AlpinistState = @AlpinistState
