##[=[
if ccinfo.is_emscripten then
  cflags '--preload-file resources'
  cflags '--shell-file shell_minimal.html'

  cflags [[-s SDL2_IMAGE_FORMATS='["png"]']]
  cflags [[-s SDL2_MIXER_FORMATS='["ogg"]']]

  cflags '-s ALLOW_MEMORY_GROWTH=1'
end
]=]

## if ccinfo.is_emscripten then
global function emscripten_set_main_loop(func: function(), fps: cint, simulate_infinite_loop: cint) <cimport,cinclude'<emscripten.h>',nodecl> end
## end
